@startuml chap5-dynamics

(*) --> "尝试加载用户的班级动态"

if "用户是否已加入班级" then
  -->[是] "加载并显示用户的班级动态"
  --> ==loaded==
else
  -->[否] "显示班级动态为空"
  --> ==loaded==
endif

==loaded== --> "进入个人设定页面"
  --> "保存个人设定"
  --> ==loaded==

==loaded== --> "进入班级管理页面"
if "用户是否已加入班级" then
  -->[是] "加载并显示班级详情"
else
  -->[否] "显示加入或创建班级的对话框"
  if "加入或创建成功" then
    -->[是] "加载并显示班级详情"
  else
    -->[否] "显示加入或创建班级的对话框"
endif
"显示加入或创建班级的对话框" --> ==loaded==
"加载并显示班级详情" --> "尝试加载用户的班级动态"

@enduml
