@startuml chap5-tomato

(*) --> "加载用户的记录信息"
  --> "显示记录到界面上\n可使用搜索栏过滤"
  --> "进入兑换奖励页面或\n日常奖惩页面"
  --> "加载奖励列表\n或奖惩列表"
  --> "显示奖励列表\n或奖惩列表"

"显示奖励列表\n或奖惩列表" --> "进入奖励或奖惩添加页面"
  --> "添加奖励或奖惩"
  --> "加载奖励列表\n或奖惩列表"
"显示奖励列表\n或奖惩列表" --> "进入奖励或奖惩详情页面"

"进入奖励或奖惩详情页面" --> "保存奖励或奖惩"
  --> "加载奖励列表\n或奖惩列表"
"进入奖励或奖惩详情页面" --> "删除奖励或奖惩"
  --> "加载奖励列表\n或奖惩列表"
"进入奖励或奖惩详情页面" --> "记录奖励或奖惩"
  --> "加载用户的记录信息"

@enduml
