@startuml chap5-task

(*) --> "加载用户的任务信息"

if "this.state.tasks" then
  -->[为空] "提示用户添加任务"
  --> "进入任务添加页面"
  --> "添加任务"
  --> "加载用户的任务信息"
else
  -->[非空] "展示任务到界面上"
  --> "进入任务添加页面"
endif

"展示任务到界面上" --> "日程视图"
--> "展示任务到界面上"

"日程视图" --> "进入番茄钟页面"
--> "日程视图"

"日程视图" --> "一周视图"
"一周视图" --> "日程视图"

"日程视图" --> "点击任务卡片进入详情页"
"一周视图" --> "点击任务卡片进入详情页"

"点击任务卡片进入详情页" --> "编辑任务"
--> "加载用户的任务信息"

"点击任务卡片进入详情页" --> "删除任务"
--> "加载用户的任务信息"

@enduml
